# Generated by Django 5.2.3 on 2025-06-22 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('banco', 'Banco'), ('red_social', 'Red Social'), ('correo', 'Correo Electrónico')], max_length=20)),
                ('nombre_servicio', models.CharField(max_length=100, verbose_name='Nombre del Servicio/Plataforma')),
                ('identificador_usuario', models.CharField(max_length=255, verbose_name='Email o Nombre de Usuario')),
                ('contrasena', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('usuario_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
